import React from 'react';
import { ShieldAlert } from 'lucide-react';

export const DisclaimerBanner = ({ compact = false }) => {
  if (compact) {
    return (
      <div className="flex items-center gap-2 p-2.5 bg-amber-50/90 dark:bg-amber-950/40 border border-amber-200/80 dark:border-amber-800/60 rounded-lg text-xs text-amber-900 dark:text-amber-200">
        <ShieldAlert className="w-4 h-4 text-amber-600 dark:text-amber-400 flex-shrink-0" />
        <p>
          <span className="font-semibold">Clinical Disclaimer:</span> This prototype is intended for screening support and research demonstration only. It does not provide a medical diagnosis.
        </p>
      </div>
    );
  }

  return (
    <div className="flex items-start gap-3 p-4 bg-gradient-to-r from-amber-50 to-orange-50/60 dark:from-amber-950/40 dark:to-slate-900 border border-amber-200 dark:border-amber-800/60 rounded-xl shadow-sm text-sm text-amber-950 dark:text-amber-100">
      <div className="p-2 bg-amber-100/90 dark:bg-amber-900/50 rounded-lg text-amber-700 dark:text-amber-300 flex-shrink-0 mt-0.5">
        <ShieldAlert className="w-5 h-5" />
      </div>
      <div>
        <h4 className="font-semibold text-amber-900 dark:text-amber-200 text-sm mb-0.5">Medical Research &amp; Ethical Screening Disclaimer</h4>
        <p className="text-amber-800 dark:text-amber-200/90 text-xs leading-relaxed">
          <span className="font-semibold">This prototype is intended for screening support and research demonstration only. It does not provide a medical diagnosis.</span>{' '}
          Predictions generated by Classical or Quantum Machine Learning models are probabilistic risk estimations for comparative research and must never be used as a substitute for professional clinical evaluation.
        </p>
      </div>
    </div>
  );
};

export default DisclaimerBanner;

